### ISSUE TITLE
error in step1

### ISSUE THREAD

**Issue by feiyuzj** [00a1/osumapper_reproduce_pytorch#1]
![24-12-09 004050](https://github.com/user-attachments/assets/67bb2d6b-9bdc-4353-bf82-7eb48a6f79b3)

please help.
same error in kotritrona's code.

**Comment by 00a1** [comment]
Replace step1 with this 
```
!pip install tensorflow==2.13.1
%cd /content/
!git clone --depth=1 -b main https://github.com/00a1/osumapper_reproduce_pytorch.git
%cd osumapper_reproduce_pytorch/osumapper_v7.0_reproduce_pytorch/maper
!apt install -y nodejs
!cp package_colab.json package.json
!pip install gradio==3.14.0
!sudo apt-get install npm
!npm install
```

**Comment by feiyuzj** [comment]
> Replace step1 with this
> 
> ```
> !pip install tensorflow==2.13.1
> %cd /content/
> !git clone --depth=1 -b main https://github.com/00a1/osumapper_reproduce_pytorch.git
> %cd osumapper_reproduce_pytorch/osumapper_v7.0_reproduce_pytorch/maper
> !apt install -y nodejs
> !cp package_colab.json package.json
> !pip install gradio==3.14.0
> !sudo apt-get install npm
> !npm install
> ```


thanks!
it works.
